### ISSUE TITLE
bayesian-optimization

### ISSUE THREAD

**Issue by msultanmahmud** [thuijskens/bayesian-optimization#4]
When I run the 

rc('text', usetex=False)
plot_iteration(lambdas, xp, yp, first_iter=3, second_param_grid=gammas, optimum=[0.58333333, -2.15789474])

it showed the following issue. Could you please let me know, how can I resolve it.
![image](https://user-images.githubusercontent.com/50304045/58040148-59e36c00-7afa-11e9-9cd7-5ef1b25d2ff6.png)

**Comment by HuabingWang-stack** [comment]
Add the following in import part of plotters.py
`import gp`
and then restart the kernel and run the code again of jupyter notebook

**Comment by HuabingWang-stack** [comment]
> When I run the
> 
> rc('text', usetex=False)
> plot_iteration(lambdas, xp, yp, first_iter=3, second_param_grid=gammas, optimum=[0.58333333, -2.15789474])
> 
> it showed the following issue. Could you please let me know, how can I resolve it.
> ![image](https://user-images.githubusercontent.com/50304045/58040148-59e36c00-7afa-11e9-9cd7-5ef1b25d2ff6.png)

Add 
`import gp`
`from sklearn import gaussian_process`

Change line 44
`kernel = gp.kernels.Matern()`
 `model = gp.GaussianProcessRegressor(kernel=kernel, alpha=alpha,                                     n_restarts_optimizer=10,normalize_y=True)`
To 
`kernel = gaussian_process.kernels.Matern()`
`model = gaussian_process.GaussianProcessRegressor(kernel=kernel,  alpha=alpha, n_restarts_optimizer=10,normalize_y=True)`
-cheers
